language: node_js
node_js:
- '0.10'
before_install:
- gem update --system
- gem install sass --version "=3.3.7"
- gem install compass --version "=0.12.3"
- npm install -g grunt-cli
install: npm install
before_script: grunt build

env:
  global:
  - secure: fH0LA0BEkxNq55AyYXJQtfpqMaynrV3YQ8hVRle2Qmz/kKZNruc/rzyc96pXz3tVZpv6yIyLYcxe+I12QnWz8ue0YAAtI4pXgl/VWmEqhHseIsdQriwoIqHyuAx0n50Optu1ZU3XExct7dO1qQJFca0gM81TSlB6K+Q4REYqJtg=
  - secure: XHfe0g0v6oLzBQTVQa7LifI9GBtbS0clCCYnlXwV6WChJfmBMoYpqYAAUfA7DJIEugYLiInhdAItLsi1s04pUaLK1Jx7AXK+L/RBZkpNqiuiHqimCIf2BHYXJfsVUqAaiueSMssgVl1XTm/eZLhGPBKuxYfZ4/09qQxePsNtyvQ=
  - secure: gHkjfV0xQjeUSdFU7Z+h0VIG/KRixLw218bGwinVLdWjAYnkLUV8xWaI/NZ/VkRf/qsN7Z6MU8w70utiY6xu+eiXPzgM/ZBcq867sMS20dfyBZNr1BCQ1qDWmCla5+D8oWmwLHm6ga9WHmuVzEYY/sJzdrRKin4n8uAMqrSSt8k=
  - secure: GZLTRtGGNrypoXgoAd59hVc3dFnsnoOu3RoOwSjeP2J7DK/wXrNYc64nM7LnmudnPA8yXTv4YZVmlqdcoNk3YaxGTS5ilQ7r4vrLk54q/SbhVVTJqJauSR0JRemjDKNhPjutB4QxxYgscbZ2INEtk1+tJRHUJfOeyEKlPBCZV/U=

after_success: find $TRAVIS_BUILD_DIR/dist/. -type f -exec curl -u $DEPLOY_USERNAME:$DEPLOY_PASSWORD --ftp-create-dirs -T {} ftp://$DEPLOY_HOST/$DEPLOY_REMOTEDIR \;
