language: node_js
node_js:
- '0.10'
before_install:
- gem update --system
- gem install sass --version "=3.3.7"
- gem install compass --version "=0.12.3"
- npm install -g grunt-cli
install: npm install
before_script: grunt build

env:
  global:
    secure: KkXRvm3nrL9EgCvNXyrP1Iovx23ja5AVTcXGg/hLpRoTUCGDRfJo4lcwLy1cNoYYZNrJQMOwGgKiUDhzq5abAwLSpnyW51TlzCbDl12f8brgtGLtVPD/1zBWRe0IQJsjyxFNZO582v9vP9HkEQqvMD7id18iTwI2EhzDbBjs9Vg=


after_success: 
- cd $TRAVIS_BUILD_DIR/dist/
- find . -type f -exec curl -u $DEPLOY_USERNAME:$DEPLOY_PASSWORD --ftp-create-dirs -T {} $DEPLOY_HOST/$DEPLOY_REMOTEDIR/{} \;
